name: semantic_search_backend
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.5=h923df54_0
  - openssl=3.0.17=hee2dfae_0
  - pip=25.2=pyhc872135_1
  - python=3.11.13=hbff2529_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cohere==5.20.0
      - dnspython==2.8.0
      - email-validator==2.3.0
      - fastapi==0.121.1
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.3.1
      - fastavro==1.12.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==1.1.2
      - idna==3.11
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - packaging==24.2
      - pinecone==7.3.0
      - pinecone-plugin-assistant==1.8.0
      - pinecone-plugin-interface==0.0.7
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.6
      - sentry-sdk==2.43.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.49.3
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - types-requests==2.32.4.20250913
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
prefix: /opt/miniconda3/envs/semantic_search_backend
