services:
  # A Docker web service
  - type: web
    name: most-similar-movies-backend
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: conda env update -f environment.yml
    startCommand: uvicorn main:app --host 0.0.0.0 --port
