name: semantic_search_preprocess
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311h1854d6b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h37d8d59_0
  - libcxx=19.1.7=haebbb44_3
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libffi=3.4.4=hecd8cb5_1
  - libsodium=1.0.20=hfdf4475_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h230baf5_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311h62e9434_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h0ab6910_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.2=py311hf197a57_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4b97444_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cohere==5.20.0
      - fastavro==1.12.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==1.1.2
      - idna==3.11
      - numpy==2.3.4
      - packaging==24.2
      - pandas==2.3.3
      - pinecone==7.3.0
      - pinecone-plugin-assistant==1.8.0
      - pinecone-plugin-interface==0.0.7
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - shellingham==1.5.4
      - sniffio==1.3.1
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - types-requests==2.32.4.20250913
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /opt/miniconda3/envs/semantic_search_preprocess
